{{- if eq .Values.snap.enabled true }}
apiVersion: snapscheduler.backube/v1
kind: SnapshotSchedule
metadata:
  name: mongo
spec:
  # A LabelSelector to control which PVCs should be snapshotted
  {{- if .Values.snap.claimSelector }}
  claimSelector:
    matchLabels:
  {{- toYaml .Values.snap.claimSelector | nindent 6 }}
  {{- end }}
  # Set to true to make the schedule inactive
  disabled: false  # optional
  retention:
    {{- if .Values.snap.retention }}
    expires: {{ .Values.snap.retention | quote }}
    {{- end }}
    {{- if .Values.snap.maxCount  }}
    maxCount: {{ .Values.snap.maxCount }}
    {{- end }}    
  schedule: {{ .Values.snap.schedule | quote }}
  snapshotTemplate:
    {{- if .Values.snap.snapshotClassName }}
    snapshotClassName: {{ .Values.snap.snapshotClassName }}
    {{- end }}    
{{- end }}