{{- if eq .Values.prisma.enabled true }}
{{- $baseuri := print .Values.protocol "://" .Values.domain }}
{{- if .Values.port }}
  {{- $baseuri := print .Values.protocol "://" .Values.domain ":" .Values.port }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma
spec:
  replicas: 1
  selector:
    matchLabels:
      role: prisma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        role: prisma
    spec:
      containers:
        - name: prisma
          image: {{ default "calendso/calendso" .Values.image | quote }}
          command: ["npx", "prisma", "studio"]
          imagePullPolicy: Always
          ports:
            - containerPort: 5555
          env:
            - name: DATABASE_URL
              value: postgresql://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@calendso-postgresql/{{ .Values.postgresql.postgresqlDatabase }}
---
apiVersion: v1
kind: Service
metadata:
  name: prisma
  labels:
    name: prisma
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 5555
      name: www
  selector:
    role: prisma
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prisma-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
{{- if eq .Values.protocol "https" }}
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
  {{- if .Values.certificate.tlsSecret }}
    traefik.ingress.kubernetes.io/router.tls: "true"
  {{- end }}
  {{- if .Values.certificate.certresolver }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.certificate.certresolver | quote }}
    traefik.ingress.kubernetes.io/router.tls: "true"
  {{- end }}
  {{- if .Values.certificate.certmain }}
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: {{ .Values.certificate.certmain | quote }}
  {{- end }}
  {{- if .Values.certificate.certsans }}
    traefik.ingress.kubernetes.io/router.tls.domains.0.sans: {{ .Values.certificate.certsans | quote }}
  {{- end }}
{{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
{{- end }}
spec:
  rules:
    - host: "{{ .Values.prisma.domain }}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: prisma
                port:
                  name: www
{{- end }}