{{- $domain := print (required "domain required!" .Values.domain) "." (required "domainsuffix required!" .Values.domainsuffix) }}
{{- $apidomain := $domain }}
{{- if .Values.apidomain }}
  {{- $apidomain = print .Values.apidomain "." (required "domainsuffix required!" .Values.domainsuffix) }}
{{- end }}
{{- $apiuri := print .Values.protocol "://" $apidomain }}
{{- if .Values.port }}
  {{- $dummy := set . "apiuri" .Values.protocol ":" .Values.port "://" $apidomain }}
{{- end }}
{{- $oteluri := print "http://otel." $domain ":4317" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.openflow.replicas }}
  selector:
    matchLabels:
      role: api
  strategy:
    #type: Recreate
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.openflow.port | quote }}
    spec:
      serviceAccountName: openflow-api-user
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: {{ default "openiap/openflow" .Values.openflow.image | quote }}
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.openflow.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.openflow.port }}
            - containerPort: 5858
          livenessProbe:
            httpGet:
              path: /loginproviders
              port: {{ .Values.openflow.port }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 30
          env:
            - name: getting_started_url
              value: {{ .Values.openflow.getting_started_url | quote }}
            - name: log_queries
              value: {{ .Values.openflow.log_queries | quote }}
            - name: log_aggregates
              value: {{ .Values.openflow.log_aggregates | quote }}
            - name: log_inserts
              value: {{ .Values.openflow.log_inserts | quote }}
            - name: log_updates
              value: {{ .Values.openflow.log_updates | quote }}
            - name: log_deletes
              value: {{ .Values.openflow.log_deletes | quote }}
            - name: log_otel_times
              value: {{ .Values.openflow.log_otel_times | quote }}
            - name: socket_rate_limit
              value: {{ .Values.openflow.socket_rate_limit | quote }}
            - name: socket_rate_limit_points
              value: {{ .Values.openflow.socket_rate_limit_points | quote }}
            - name: socket_rate_limit_duration
              value: {{ .Values.openflow.socket_rate_limit_duration | quote }}
            - name: api_rate_limit
              value: {{ .Values.openflow.api_rate_limit | quote }}
            - name: api_rate_limit_points
              value: {{ .Values.openflow.api_rate_limit_points | quote }}
            - name: api_rate_limit_duration
              value: {{ .Values.openflow.api_rate_limit_duration | quote }}
            - name: supports_watch
              value: {{ .Values.openflow.supports_watch | quote }}
            - name: ensure_indexes
              value: {{ .Values.openflow.ensure_indexes | quote }}
            - name: license_key
              value: {{ default "" .Values.openflow.license_key | quote }}
            - name: stripe_api_key
              value: {{ default "" .Values.openflow.stripe_api_key | quote }}
            - name: stripe_api_secret
              value: {{ default "" .Values.openflow.stripe_api_secret | quote }}
            - name: NODE_ENV
              value: {{ default "" .Values.NODE_ENV | quote }}
            - name: nodered_initial_liveness_delay
              value: {{ .Values.openflow.nodered_initial_liveness_delay | quote }}
            - name: multi_tenant
              value: {{ .Values.openflow.multi_tenant | quote }}
            - name: update_acl_based_on_groups
              value: {{ .Values.openflow.update_acl_based_on_groups | quote }}
            - name: websocket_package_size
              value: {{ .Values.openflow.websocket_package_size | quote }}
            - name: websocket_max_package_count
              value: {{ .Values.openflow.websocket_max_package_count | quote }}
            - name: nodered_image
              value: {{ .Values.openflow.nodered_image | quote }}
            - name: amqp_force_queue_prefix
              value: {{ .Values.openflow.force_queue_prefix | quote }}
            - name: amqp_force_exchange_prefix
              value: {{ .Values.openflow.force_queue_prefix | quote }}
            - name: namespace
              value: {{ .Release.Namespace | quote }}
            - name: allow_personal_nodered
              value: {{ .Values.openflow.allow_personal_nodered | quote }}
            - name: auto_create_personal_nodered_group
              value: {{ .Values.openflow.auto_create_personal_nodered_group | quote }}
            - name: nodered_domain_schema
              value: "$nodered_id$.{{ $domain }}"
            - name: protocol
              value: {{ .Values.protocol | quote }}
            - name: port
              value: {{ .Values.openflow.port | quote }}
            - name: skip_history_collections
              value: {{ .Values.openflow.skip_history_collections | quote }}
            - name: tls_passphrase
              value: {{ default "" .Values.openflow.tls_passphrase | quote }}
            - name: auto_create_users
              value: {{ .Values.openflow.auto_create_users | quote }}
            - name: auto_create_domains
              value: {{ default "" .Values.openflow.auto_create_domains | quote }}
            - name: allow_user_registration
              value: {{ .Values.openflow.allow_user_registration | quote }}
            - name: persist_user_impersonation
              value: {{ .Values.openflow.persist_user_impersonation | quote }}
            - name: aes_secret
              value: {{ .Values.openflow.aes_secret | quote }}
            - name: tls_crt
              value: {{ default "" .Values.openflow.tls_crt | quote }}
            - name: tls_key
              value: {{ default "" .Values.openflow.tls_key | quote }}
            - name: tls_ca
              value: {{ default "" .Values.openflow.tls_ca | quote }}
            - name: signing_crt
              value: {{ .Values.openflow.signing_crt | quote }}
            - name: singing_key
              value: {{ .Values.openflow.singing_key | quote }}
            - name: saml_federation_metadata
{{- if .Values.openflow.saml_federation_metadata }}
              value: {{ .Values.openflow.saml_federation_metadata | quote }}
{{- else }}
              value: "{{ $apiuri }}/issue/FederationMetadata/2007-06/FederationMetadata.xml"
{{- end }}
            - name: saml_issuer
              value: "uri:{{ $apidomain }}"
{{- if .Values.mongodb.enabled }}
  {{- if eq .Values.mongodb.architecture "replicaset" }}
            - name: mongodb_url
              value: "mongodb://openflow:supersecret@openflow-mongodb-headless:27017/{{ .Values.mongodb.auth.database }}?replicaSet={{ .Values.mongodb.replicaSetName }}"
            - name: mongodb_db
              value: {{ .Values.mongodb.auth.database | quote }}
  {{- else }}
            - name: mongodb_url
              value: "mongodb://openflow:supersecret@openflow-mongodb:27017/{{ .Values.mongodb.auth.database }}"
            - name: mongodb_db
              value: {{ .Values.mongodb.auth.database | quote }}
  {{- end }}
{{- else }}
            - name: mongodb_url
              value: {{ required "A valid .Values.openflow.external_mongodb_url entry required!" .Values.openflow.external_mongodb_url | quote }}
  {{- if .Values.openflow.mongodb_db }}
            - name: mongodb_db
              value: {{ .Values.openflow.mongodb_db  | quote }}
  {{- else }}
            - name: mongodb_db
              value: {{ .Release.Namespace | quote }}
  {{- end }}
{{- end }}
            - name: mongodb_minpoolsize
              value: {{ .Values.openflow.mongodb_minpoolsize  | quote }}
            - name: amqp_url
              value: "amqp://{{ .Values.rabbitmq.default_user }}:{{ .Values.rabbitmq.default_pass }}@rabbitmq"
            - name: api_ws_url
              value: {{ .Values.openflow.api_ws_url  | quote }}
            - name: domain
              value: "{{ $apidomain }}"
            - name: nodered_allow_nodeselector
              value: {{ .Values.openflow.nodered_allow_nodeselector | quote }}
            - name: nodered_requests_memory
              value: {{ .Values.openflow.nodered_requests_memory  | quote }}
            - name: nodered_requests_cpu
              value: {{ .Values.openflow.nodered_requests_cpu  | quote }}
            - name: nodered_limits_memory
              value: {{ .Values.openflow.nodered_limits_memory  | quote }}
            - name: nodered_limits_cpu
              value: {{ .Values.openflow.nodered_limits_cpu  | quote }}
            - name: nodered_liveness_failurethreshold
              value: {{ .Values.openflow.nodered_liveness_failurethreshold  | quote }}              
            - name: prometheus_measure_nodeid
              value: {{ .Values.openflow.prometheus_measure_nodeid  | quote }}
            - name: prometheus_measure_queued_messages
              value: {{ .Values.openflow.prometheus_measure_queued_messages  | quote }}
            - name: prometheus_measure__mongodb_watch
              value: {{ .Values.openflow.prometheus_measure__mongodb_watch  | quote }}
            - name: prometheus_measure_onlineuser
              value: {{ .Values.openflow.prometheus_measure_onlineuser  | quote }}
            - name: enable_analytics
              value: {{ .Values.openflow.enable_analytics  | quote }}
{{- if .Values.openflow.otel_trace_url }}
            - name: otel_trace_url
              value: {{ .Values.openflow.otel_trace_url  | quote }}
{{- else }}
            - name: otel_trace_url
              value: "{{ $oteluri }}"
{{- end }}
{{- if .Values.openflow.otel_metric_url }}
            - name: otel_metric_url
              value: {{ .Values.openflow.otel_metric_url  | quote }}
{{- else }}
            - name: otel_metric_url
              value: "{{ $oteluri }}"
{{- end }}
            - name: otel_servicename
              value: {{ .Values.openflow.otel_servicename  | quote }}
            - name: otel_trace_interval
              value: {{ .Values.openflow.otel_trace_interval  | quote }}
            - name: otel_metric_interval
              value: {{ .Values.openflow.otel_metric_interval  | quote }}
            - name: expected_max_roles
              value: {{ .Values.openflow.expected_max_roles  | quote }}
            - name: max_recursive_group_depth
              value: {{ .Values.openflow.max_recursive_group_depth  | quote }}              
            - name: decorate_roles_fetching_all_roles
              value: {{ .Values.openflow.decorate_roles_fetching_all_roles  | quote }}              
            - name: roles_cached_in_seconds
              value: {{ .Values.openflow.roles_cached_in_seconds  | quote }}              
            - name: validate_user_form
              value: {{ .Values.openflow.validate_user_form  | quote }}              
            - name: DEBUG
              value: {{ .Values.openflow.debug  | quote }}              
            - name: shorttoken_expires_in
              value: {{ .Values.openflow.shorttoken_expires_in  | quote }}              
            - name: longtoken_expires_in
              value: {{ .Values.openflow.longtoken_expires_in  | quote }}              
            - name: downloadtoken_expires_in
              value: {{ .Values.openflow.downloadtoken_expires_in  | quote }}              
            - name: personalnoderedtoken_expires_in
              value: {{ .Values.openflow.personalnoderedtoken_expires_in  | quote }}              
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      role: rabbitmq
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: rabbitmq
        environment: production
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: rabbitmq
          #image: rabbitmq:3-management
          image: rabbitmq:3.8.3-management
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
          ports:
            - containerPort: 5672
              name: rabbitmq
            - containerPort: 15672
              name: rabbitmq-mgnt
          env:
          {{- if .Values.rabbitmq.vm_memory_high_watermark }}
            - name: RABBITMQ_VM_MEMORY_HIGH_WATERMARK
              value: {{ .Values.rabbitmq.vm_memory_high_watermark }}
          {{- end }}
            - name: RABBITMQ_DEFAULT_USER
              value: {{ required "A valid .Values.rabbitmq.default_user entry required!" .Values.rabbitmq.default_user }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ required "A valid .Values.rabbitmq.default_pass entry required!" .Values.rabbitmq.default_pass }}
