apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  type: NodePort
#  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.openflow.port }}
      name: www
  selector:
    role: api
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 5672
      targetPort: 5672
      name: rabbitmq
    - port: 80
      targetPort: 15672
      name: web
    - port: 15672
      targetPort: 15672
      name: rabbitmq-mgnt
  selector:
    role: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: api-grpc
  labels:
    name: api-grpc
  annotations:  
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
spec:
  # type: NodePort
#  sessionAffinity: ClientIP
  # clusterIP: None 
  ports:
    - port: {{ .Values.grpc.internalport }}
      name: grpc
  selector:
    role: api
---
